[package]
name = "mimir"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
fs = "0.0.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
clap_complete = "4.5"
anyhow = "1.0.100"
dirs = "6.0.0"
walkdir = "2.5.0"
